"use strict";
const fs = require("fs");
const path = require("path");
const root = path.resolve(__dirname, "..");
const scenes = JSON.parse(fs.readFileSync(path.join(root, "src/scenes.json"), "utf8"));
const concept = fs.readFileSync(path.join(root, "src/gfx/ConceptCompositions.tsx"), "utf8");
const primitives = fs.readFileSync(path.join(root, "src/gfx/ConceptPrimitives.tsx"), "utf8");
const sentence = fs.readFileSync(path.join(root, "src/scene/SentenceSequence.tsx"), "utf8");
const sfx = fs.readFileSync(path.join(root, "src/sfx.ts"), "utf8");
const fail = (message) => { throw new Error(`source-audit: ${message}`); };
const assert = (value, message) => { if (!value) fail(message); };
const code = scenes.scenes.filter((s) => s.kind === "CODE");
const photo = scenes.scenes.filter((s) => s.kind === "PHOTO");
assert(scenes.totalFrames === 12278, "totalFrames must remain 12278");
assert(scenes.scenes.length === 108 && code.length === 30 && photo.length === 78, "expected 108 scenes / 30 CODE / 78 PHOTO");
assert(JSON.stringify(code.map((s) => s.content.form)) === JSON.stringify([...Array(30).keys()]), "forms must be exactly 0..29");
for (let i=0;i<30;i++) assert(concept.includes(`form-${i}:`), `missing semantic composition marker form-${i}`);
assert(/left:\s*110[\s\S]*right:\s*1810[\s\S]*top:\s*70[\s\S]*bottom:\s*940/.test(primitives), "safe constants changed");
assert(/TITLE_MIN_PX\s*=\s*48/.test(primitives) && /BODY_MIN_PX\s*=\s*38/.test(primitives), "type minimums changed");
assert(/OBJECT_LABEL_MAX_Y\s*=\s*900/.test(primitives), "object labels may not enter bottom 140px");
assert(!/bottom\s*:/.test(concept), "concept labels must not use bottom positioning");
assert(/\[0,\s*15\]/.test(sentence) && /scene\.duration \+ 15/.test(sentence), "sentence crossfade/overlap must be 15 frames");
const cues = [...sfx.matchAll(/\{frame:\s*(\d+),\s*file:\s*"([^"]+)",\s*volume:\s*([0-9.]+)\}/g)].map((m)=>({frame:+m[1],file:m[2],volume:+m[3]}));
assert(cues.length >= 8 && cues.length <= 10, "expected 8-10 SFX cues");
assert(cues.every((c,i)=>c.frame>0 && (!i || c.frame>cues[i-1].frame)), "SFX frames must be increasing absolute landings");
assert(cues.every((c)=>c.file === "08_ui_sounds.wav" || c.file === "04_menu_camera_click.wav"), "unsupported SFX file");
assert(cues.every((c)=>c.volume <= (c.file === "08_ui_sounds.wav" ? .10 : .08)), "SFX volume exceeds cap");
for (const file of new Set(cues.map((c)=>c.file))) assert(fs.existsSync(path.join(root,"public/sfx",file)), `missing public/sfx/${file}`);
console.log("source-audit: PASS — 30 semantic forms, immutable timeline counts, safe typography/bounds, crossfade, and 9 sparse cues");
